# This script is used to build the docker image, run the docker container and mount a volume to the host machine.
# The volume is used to store the graphs generated by the python script.

echo "# ------------------------------------------------------------------#"
echo "#  Polytechnique Montreal                                           #"
echo "# ------------------------------------------------------------------#"
 
echo ""
echo "=============================================="
echo "|                  LOG8415E                  |"
echo "|                     TP1                    |"
echo "|         1895231 - Anis Youcef Dilmi        |"
echo "|         2224721 - Mohammed Ridha Ghoul     |"
echo "|         1954607 - Victor Kim               |"
echo "|         2225733 - Yasser Benmansour        |"
echo "=============================================="
echo ""
docker build -t lab_1 .

docker run -it --env-file ./.aws_creds --volume "$(pwd)/graphs:/graphs" lab_1
